package com.courigistics.courigisticsbackend.entities.enums;

public enum DeliveryStatus {
    CREATED, PENDING_PAYMENT, PAID, OFFERED, AT_ORIGIN_DEPOT, ASSIGNED,
    ARRIVED_AT_PICKUP, PICKED_UP, IN_TRANSIT, ARRIVED_AT_DROPOFF,
    AT_DESTINATION_DEPOT, OUT_FOR_DELIVERY,
    DELIVERED, FAILED, CANCELLED, STORED_AT_DEPOT
}
